### ISSUE TITLE
starting podman on macOS no Rosetta fails

### ISSUE THREAD

**Issue by altitudedashboard** [containers/gvisor-tap-vsock#122]
I'm not using brew or macports. I installed everything manually (qemu 7.0 and go 1.18.2 installed) and then built podman:

cd ~
curl -LJO https://github.com/containers/gvisor-tap-vsock/releases/download/v0.3.0/gvproxy-darwin
sudo mv gvproxy-darwin /usr/local/bin/gvproxy
sudo chown root:wheel /usr/local/bin/gvproxy
sudo chmod +x /usr/local/bin/gvproxy

cd ~
curl -LJO https://github.com/containers/podman/releases/download/v4.1.0/podman-remote-release-darwin_arm64.zip
unzip podman-remote-release-darwin_arm64.zip
sudo mv podman-4.1.0/usr/bin/podman /usr/local/bin
sudo chown root:wheel /usr/local/bin/podman
sudo chown root:wheel podman-4.1.0/docs/*
sudo mv podman-4.1.0/docs/* /usr/local/share/man/man1/
sudo chmod -x /usr/local/share/man/man1/podman*
rm -rf podman-4.1.0
rm podman-remote-release-darwin_arm64.zip

Starting fails:

podman machine start
Starting machine "podman-machine-default"
Error: unable to start host networking: "unable to execute: [\"/usr/local/bin/gvproxy\" \"-listen-qemu\" \"unix:///var/folders/fn/jnzlnk8n7r92yp0r5n12m_0m0000gn/T/podman/qmp_podman-machine-default.sock\" \"-pid-file\" \"/var/folders/fn/jnzlnk8n7r92yp0r5n12m_0m0000gn/T/podman/podman-machine-default.pid\" \"-ssh-port\" \"54461\" \"-forward-sock\" \"/Users/codrut/.local/share/containers/podman/machine/podman-machine-default/podman.sock\" \"-forward-dest\" \"/run/user/501/podman/podman.sock\" \"-forward-user\" \"core\" \"-forward-identity\" \"/Users/codrut/.ssh/podman-machine-default\"]: fork/exec /usr/local/bin/gvproxy: bad CPU type in executable"

it looks like the problem is:

file /usr/local/bin/gvproxy
/usr/local/bin/gvproxy: Mach-O 64-bit executable x86_64

however I have not found a way to compile gvproxy for macOS M1

**Comment by baude** [comment]
it looks like gvproxy should create both an arm64 and amd64 binary ?

**Comment by gbraad** [comment]
We merged #130 to resolve this. However, the lack of proper tests prevents me to create a release at the moment. Running manual tests

**Comment by cfergeau** [comment]
The 0.4.0 has #130, closing this.
