### ISSUE TITLE
Support for Darwin 22

### ISSUE THREAD

**Issue by MBartsch71** [containers/gvisor-tap-vsock#155]
When I try to install gvisor-tap-vsock on MacOS Ventura, it fails with the following error message in the main.log file.

:info:archivefetch --->  gvisor-tap-vsock-0.4.0_0.darwin_22.arm64.tbz2 doesn't seem to exist in /opt/local/var/macports/incoming/verified
  19   │ :msg:archivefetch --->  Attempting to fetch gvisor-tap-vsock-0.4.0_0.darwin_22.arm64.tbz2 from https://packages.macports.org/gvisor-tap-vsock
  20   │ :debug:archivefetch Fetching archive failed: The requested URL returned error: 404

Is there an estimation when the support for darwin22 is provided?

Thanks in advance

**Comment by cfergeau** [comment]
The gvisor-tap-vsock build in macports is not maintained here
https://ports.macports.org/port/gvisor-tap-vsock/details/
Can you file an issue against macports ? https://trac.macports.org/newticket?port=gvisor-tap-vsock

**Comment by judaew** [comment]
This ticket https://trac.macports.org/ticket/66152 should fix building gvisor-tap-vsock.
