### ISSUE TITLE
Release 0.5.0 has no assets published

### ISSUE THREAD

**Issue by arixmkii** [containers/gvisor-tap-vsock#170]
With the latest release https://github.com/containers/gvisor-tap-vsock no assets could be found. Only the source tar.gz and zip files are there.

Is it expected? I'm updating documentation in one of Podman tutorials (manually configuring remote to QEMU VM on Windows) and I need to complete the section about gvproxy. Should I just mention that it is responsibility of the user to prepare gvproxy binary and give instructions how to achieve this?

**Comment by cfergeau** [comment]
That's an oversight, I'll add these.

**Comment by cfergeau** [comment]
I've added the gvproxy-* binaries, is this enough or do you also need qemu-wrapper?

**Comment by arixmkii** [comment]
@cfergeau thank you! It is enough. I will later create a PR to update README file to highlight that since QEMU 7.2.0 it is possible to use new qapi to connect gvproxy and QEMU w/o qemu-wrapper.
