### ISSUE TITLE
Why does iperf3 measure asymmetric throughput?

### ISSUE THREAD

**Issue by NullHypothesis** [containers/gvisor-tap-vsock#211]
I'm working on [a project](https://github.com/brave/nitriding-daemon) that builds on top of gvisor-tap-vsock. I reproduced [your iperf3 throughput measurements](https://github.com/containers/gvisor-tap-vsock#performance) and noticed that server-to-client traffic is about 3x faster than client-to-server traffic—at least in our more complex test setup.

The README says "[...] depending on which side the test is performed [...]", so this is not news to you. I wonder however why that is? What exactly contributes to the throughput being asymmetric?

**Comment by cfergeau** [comment]
Guillaume who ran these tests and added this to the README is no longer active on gvisor-tap-vsock, so I'm afraid this knowledge was lost :-/

**Comment by NullHypothesis** [comment]
> Guillaume who ran these tests and added this to the README is no longer active on gvisor-tap-vsock, so I'm afraid this knowledge was lost :-/

Having studied the code for a while, I can now answer my own question. The [send](https://github.com/containers/gvisor-tap-vsock/blob/86f3f8f3acfd163d193249e0d78437b2bde86d94/pkg/tap/switch.go#L113) and [receive](https://github.com/containers/gvisor-tap-vsock/blob/86f3f8f3acfd163d193249e0d78437b2bde86d94/pkg/tap/switch.go#L196) path for network packets differs in non-trivial ways. The same is true for the tools cmd/gvproxy and cmd/vm. I haven't measured the exact overhead but I'm fairly confident that this explains the difference. See [this PR](https://github.com/containers/gvisor-tap-vsock/pull/215) for some additional context.
