### ISSUE TITLE
Add vfkit support

### ISSUE THREAD

**Issue by cfergeau** [containers/gvisor-tap-vsock#224]
vfkit can transfer guest network data directly to the host through a unix datagram socket, but gvproxy/... do not have support for datagram sockets. This support would need to be added.

**Comment by balajiv113** [comment]
I actually tried providing this support when working on lima-vm vz driver. But looked too much work.

So we provide this support in lima-vm already via datagram socketpair (which is a connected socket no need to use readFrom / writeTo). So the existing code works well via this modal. We just need to use AcceptBess() non-streaming connection

Just adding incase if this approach looks interesting for your usecase as well.

**Comment by cfergeau** [comment]
I made some progress towards that in https://github.com/cfergeau/gvisor-tap-vsock/commit/42a6987c19b9fd008e26e22ff0b28d825e8408c9 but this needs more work, as under 'heavy' traffic ("podman pull ..." inside the VM), I'm getting write errors ("sendto buffer full" or such).

> So we provide this support in lima-vm already via datagram socketpair

I'll look at this, this sounds interesting and might be enough for what I want!

**Comment by cfergeau** [comment]
I filed https://github.com/containers/gvisor-tap-vsock/pull/231

**Comment by cfergeau** [comment]
#231 has been merged.
