### ISSUE TITLE
stopping gvproxy

### ISSUE THREAD

**Issue by baude** [containers/gvisor-tap-vsock#255]
Right now, to stop gvproxy when used with things like podman, podman sends a sigkill to gvproxy.  in golang, when sigkill is sent, defers and cleanup routines are not executed and this often results in file and socket turds laying around.

I am wondering if it would be better to not depend on sending signals to stop gvproxy. perhaps consider adding it to the rest-api?

**Comment by baude** [comment]
@gbraad @cfergeau bump unless on pto

**Comment by cfergeau** [comment]
podman could first send `SIGSTOP`, which will cleanup files/sockets. If `gvproxy` does not go away in a reasonable time, then podman can send `SIGKILL` to get rid of the process.
I don't mind adding `exit` to the REST API, but would this be very different from `SIGSTOP`?

**Comment by baude** [comment]
imho, the rest approach would send the ctx.Done() resulting in a "graceful" shutdown?

**Comment by cfergeau** [comment]
> imho, the rest approach would send the ctx.Done() resulting in a "graceful" shutdown?

The signal approach already cancels() the context so that a `ctx.Done()` triggers https://github.com/containers/gvisor-tap-vsock/blob/26b71099aef38b80761faced9b47d31973e37356/cmd/gvproxy/main.go#L234-L244

**Comment by cfergeau** [comment]
> We need to read the pidfile, then "find" the process,

Ah right, did not think of this complication.

> then wait on the signal with a timeout; then send a kill if not dead in a certain amount of time,

Imo, you need to do this even with the REST API in case gvproxy does not react as expected to the REST command?

>  lets do that now and we can discuss in the future. this fine by me

I don't have strong objections to the REST API addition, it just felt redundant with the signal handlers we have. If you file a PR to add this to the REST API, I won't reject it :)
