### ISSUE TITLE
Document new binary requirements

### ISSUE THREAD

**Issue by afbjorklund** [containers/gvisor-tap-vsock#256]
The old `gvproxy` 0.6.2 also ran on Ubuntu 20.04 (glibc 2.31)

But the new `gvproxy` 0.7.0 requires Ubuntu 22.04 (glibc 2.35)

```
/usr/local/libexec/podman/gvproxy: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /usr/local/libexec/podman/gvproxy)
/usr/local/libexec/podman/gvproxy: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /usr/local/libexec/podman/gvproxy)
```

----

The arch variants seem to be missing, as well:

gvproxy-linux-amd64
gvproxy-linux-arm64

Building from source code instead worked...

**Comment by cfergeau** [comment]
> The old gvproxy 0.6.2 also ran on Ubuntu 20.04 (glibc 2.31)
> But the new gvproxy 0.7.0 requires Ubuntu 22.04 (glibc 2.35)

The binaries are built in github actions on an `ubuntu-latest` image, using `ubuntu-20.04` instead/in addition to `-latest` should help.

**Comment by afbjorklund** [comment]
Thanks!

**Comment by csdivad** [comment]
Maybe try building with `CGO_ENABLED=0` instead? (Would it work? Would it have any performance hit?)

**Comment by cfergeau** [comment]
> Maybe try building with `CGO_ENABLED=0` instead? (Would it work? Would it have any performance hit?)

That’s a good suggestion, I’ve filed https://github.com/containers/gvisor-tap-vsock/issues/500 to track this.
