### ISSUE TITLE
[BUG]: no route to host

### ISSUE THREAD

**Issue by BlackHole1** [containers/gvisor-tap-vsock#303]
There is a chance that I may encounter an error message `read: Connection reset by peer` when I connect to the virtual machine from the host machine via SSH.

gvproxy log:

```
2024/01/02 17:05:12 tcpproxy: for incoming conn 127.0.0.1:61639, error dialing "192.168.127.2:22": connect tcp 192.168.127.2:22: no route to host
```

If I rerun `gvforwarder` in the virtual machine, the issue will be resolved. Otherwise, the host machine will never be able to connect to the virtual machine via ssh.

Here are the observations I have made:

1. The probability of this problem occurring is very low. Once it occurs, either `gvforwarder` needs to be re-run in the virtual machine or the entire virtual machine needs to be restarted.
2. After the problem occurs, I can expose other ports in the virtual machine using `gatewayIP` (192.168.127.1) without any issues, except for ssh.
3. SSH forwarding is implemented through the `-ssh-port` in `gvproxy`.
4. After the problem occurs, I observed that the IP address of the virtual machine is **192.168.127.3**, instead of 192.168.127.2. Please refer to the image:
   ![17-02 16 17@2x](https://github.com/containers/gvisor-tap-vsock/assets/8198408/61cd80e5-8f0c-464d-a05e-c1f472cef7f5)

Through investigation, I have found that the issue lies in https://github.com/containers/gvisor-tap-vsock/blob/f01fd1c0dda648338230aa1bfd5ea894620df13d/pkg/services/dhcp/dhcp.go#L34

I have added some log codes here and obtained the following results:

```go
log.Infof("===================ip: %s, mac: %s", ip, m.ClientHWAddr.String())
log.Infof("===================ipPool: %+v", ipPool.Leases())
```

![22-02 17 22@2x](https://github.com/containers/gvisor-tap-vsock/assets/8198408/9f7e3d8a-f18e-48e0-8734-bde169262684)

My guess is related to vfkit because according to the DHCP protocol, the MAC address is sent from the client (virtual machine) to the DHCP server. In my scenario, I use vfkit's `virtio-vsock` to create the network connection (see: https://github.com/containers/gvisor-tap-vsock#macos-prerequisites). So during the entire vfkit program, I did not specify any mac address.

/cc @cfergeau @guillaumerose

**Comment by BlackHole1** [comment]
The issue has been confirmed to be unrelated to `gvisor-tap-vsock` and caused by the **99-default.link** rule in *systemd-network*.

Here is the process when the VM is experiencing issues:

1. *gvforwarder* creates the `tap0` virtual network device.
2. *udev* detects that the `addr_assign_type` of `tap0` device is `NET_ADDR_RANDOM` and prepares to set a random MAC address.
3. *gvforwarder* sets the predefined MAC address successfully.
4. *udev* sets the MAC address of tap0 to a random address.
5. *gvforwarder* initiates a DHCP request.
6. *gvproxy* receives the DHCP request but doesn’t find a matching MAC address, so it assigns the IP address `192.168.127.3`.
7. *gvproxy* attempts to set up SSH forwarding but fails due to the incorrect IP address, resulting in the termination of *gvproxy*.

By overriding the **99-default.link** rule and setting the `MACAddressPolicy` to `none`, we can avoid udev setting a random MAC address for the virtual network device.

**Comment by cfergeau** [comment]
Does this solve the whole issue? Or just point 4. in the initial description, where the VM address would become 192.168.127.3?

**Comment by cfergeau** [comment]
If you are not already aware of them, the files in https://github.com/containers/gvisor-tap-vsock/tree/main/contrib can be useful. There is a network manager config  file to pre-create the tap0 device, and a systemd unit file to start gvforwarder in the VM. This removes the need for the use of udhcpc.

**Comment by BlackHole1** [comment]
> Does this solve the whole issue?
Yes

Because `gvproxy` will automatically forward the SSH port of the VM, see:

https://github.com/containers/gvisor-tap-vsock/blob/f01fd1c0dda648338230aa1bfd5ea894620df13d/cmd/gvproxy/main.go#L229-L231

https://github.com/containers/gvisor-tap-vsock/blob/f01fd1c0dda648338230aa1bfd5ea894620df13d/cmd/gvproxy/main.go#L52

When the MAC address of the VM is not the default value, the DHCP server in the `gvproxy` will assign an unexpected IP address (192.168.127.3) to the VM, causing the automatic forwarding of SSH to be invalid. At this time, when the host machine accesses port 2223, `gvproxy` will forward its traffic to the expected IP address (192.168.127.2). However, due to the unreachable IP address, when the host machine accesses the VM via the SSH command, it will receive the "no route to host" error.

> If you are not already aware of them, the files in https://github.com/containers/gvisor-tap-vsock/tree/main/contrib can be useful. There is a network manager config file to pre-create the tap0 device, and a systemd unit file to start gvforwarder in the VM. This removes the need for the use of udhcpc.

Thank you for your reply. I am developing a minimal Linux system that can run Podman, so I haven't installed modern network management commands like `nmcli/network-manager`. So, the `nmconnection` file cannot be parsed in my system. However, the issue has been resolved now 😃.
