### ISSUE TITLE
Do not link statically by default

### ISSUE THREAD

**Issue by fweimer-rh** [containers/gvisor-tap-vsock#32]
The makefile contains this:

```
LDFLAGS = -ldflags '-s -w -extldflags "-static"'
```

This switches on fully static linking, which is not fully supported with glibc. The Go defaults should already produce statically linked binaries on targets where this feasible. But if glibc is needed for some reason, it should be linked dynamically.

**Comment by guillaumerose** [comment]
Done in https://github.com/containers/gvisor-tap-vsock/commit/10c1c081da366e9f8b2b95f54c720f6613febf9e#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52

Thanks for the suggestion!
