### ISSUE TITLE
[Question] How to run a service on a host that the guest can connect to?

### ISSUE THREAD

**Issue by DUOLabs333** [containers/gvisor-tap-vsock#361]
I was able to get gvproxy successfully running on a MacOS host, and a Linux guest to connect to the host --- `ping -c1 192.168.127.1` on the guest succeeds, and I can see the corresponding connection message on the host. However, when I tried running an `iperf3` server on the host so I can test the connection speed on the client, the client failed to connect. The server is running on `192.168.127.1`.

**Comment by cfergeau** [comment]
There is this script to test gvisor-tap-vsock performance, and it's using iperf3 https://github.com/containers/gvisor-tap-vsock/blob/main/test/performance.sh so this should work somehow. 

Be careful though, 192.168.127.1 is the network gateway IP, the host IP is 192.168.127.254. I just tested with netcat that if I run `nc -l 5050` on the host, I have to use `nc 192.168.127.254 5050` on the guest to successfully connect. Connection to port 5050 is refused if I try 192.168.127.1.

**Comment by DUOLabs333** [comment]
Starting a server on localhost on the server, and connecting to `192.168.127.254` works.
