### ISSUE TITLE
DNS forwarding code only handles the first name server

### ISSUE THREAD

**Issue by cfergeau** [containers/gvisor-tap-vsock#398]
See [pkg/services/dns/dns_config_unix.go](https://github.com/containers/gvisor-tap-vsock/pull/339/files#diff-a6c1eaa7552819ff2c7c86a8e68b8910f01a3e676d8d57d1d89b49a8357e9665):
```
	// TODO: use all configured nameservers, instead just first one
```

**Comment by balajiv113** [comment]
@cfergeau 
When the next release is planned ?? 
Need this changes to fix a possible regression.

**Comment by cfergeau** [comment]
0.8.1 has been released, let me know if it solves your issues.
