### ISSUE TITLE
Port forward should be able to expose a port on a unix socket on the host

### ISSUE THREAD

**Issue by guillaumerose** [containers/gvisor-tap-vsock#41]
Currently, only TCP port to TCP port forwarding is working. It would a great addition if a TCP port of the VM could be reachable on the host via an Unix socket.

Example usage:
Podman API can run on port 2375 and gvproxy can expose it as /var/run/docker.sock on the host.

**Comment by protosam** [comment]
What should the behavior for this look like on windows hosts?

**Comment by protosam** [comment]
Updated PR to also support unix-to-unix over SSH.

This approach opens up the ability to have the podman machine completely accessible in the forwarder service. Perhaps refactoring to remove stuff like the [ssh bastion code](https://github.com/containers/gvisor-tap-vsock/blob/3ec335bea2e933a377b4da70d33fb81c63fc07f5/pkg/sshclient/bastion.go) and [gvproxy ssh forwarder](https://github.com/containers/gvisor-tap-vsock/blob/3ec335bea2e933a377b4da70d33fb81c63fc07f5/cmd/gvproxy/ssh_forwarder.go) can be considered.

**Comment by guillaumerose** [comment]
First part is merged (unix to tcp) https://github.com/containers/gvisor-tap-vsock/pull/89

The second part is still WIP.
