### ISSUE TITLE
Panics on systems with empty /etc/resolv.conf

### ISSUE THREAD

**Issue by siretart** [containers/gvisor-tap-vsock#417]
While working on the Debian package of this project, I noticed a panic while running the testsuite of this package:

```
in Spec Setup (BeforeEach) [0.000 seconds][0m
dns add test
[90m/<<PKGBUILDDIR>>/_build/src/github.com/containers/gvisor-tap-vsock/pkg/services/dns/dns_test.go:22[0m
  [91m[1mshould add dns zone with ip [BeforeEach][0m
  [90m/<<PKGBUILDDIR>>/_build/src/github.com/containers/gvisor-tap-vsock/pkg/services/dns/dns_test.go:29[0m

  [91m[1mTest Panicked[0m
  [91mruntime error: index out of range [0] with length 0[0m
  /usr/lib/go-1.23/src/runtime/panic.go:115

  [91mFull Stack Trace[0m
  github.com/containers/gvisor-tap-vsock/pkg/services/dns.getDNSHostAndPort()
  	/<<PKGBUILDDIR>>/_build/src/github.com/containers/gvisor-tap-vsock/pkg/services/dns/dns_config_unix.go:15 +0x6c
  github.com/containers/gvisor-tap-vsock/pkg/services/dns.newDNSHandler({0xbb0d80, 0x0, 0x0})
  	/<<PKGBUILDDIR>>/_build/src/github.com/containers/gvisor-tap-vsock/pkg/services/dns/dns.go:29 +0x37
  github.com/containers/gvisor-tap-vsock/pkg/services/dns.New({0x0, 0x0}, {0x0, 0x0}, {0xbb0d80?, 0x10?, 0x1?})
  	/<<PKGBUILDDIR>>/_build/src/github.com/containers/gvisor-tap-vsock/pkg/services/dns/dns.go:166 +0x39
  github.com/containers/gvisor-tap-vsock/pkg/services/dns.init.func1.1()
  	/<<PKGBUILDDIR>>/_build/src/github.com/containers/gvisor-tap-vsock/pkg/services/dns/dns_test.go:26 +0x33
  github.com/containers/gvisor-tap-vsock/pkg/services/dns.TestSuite(0xc0000a8b60)
  	/<<PKGBUILDDIR>>/_build/src/github.com/containers/gvisor-tap-vsock/pkg/services/dns/dns_test.go:19 +0x3c
  testing.tRunner(0xc0000a8b60, 0x8825b0)
  	/usr/lib/go-1.23/src/testing/testing.go:1690 +0xf4
  created by testing.(*T).Run in goroutine 1
  	/usr/lib/go-1.23/src/testing/testing.go:1743 +0x390
[90m------------------------------[0m
[91m[1m•! Panic in Spec Setup (BeforeEach) [0.000 seconds][0m
```

This panic starts happening when upgrading to version 0.8.0. It does not occur with version 0.7.3

Looking at the code, I believe this is caused by 58eb054369873855afdc329ae724db779800cf74, which introduces https://github.com/containers/gvisor-tap-vsock/blob/72b102d1d443d6d02e4c04f5c2af809e4c2e0910/pkg/services/dns/dns_config_unix.go#L9-L17

The panic occurs in line 15 when the test machine does have an empty `/etc/resolv.conf`. This makes sense for a build machine to attempt to disable connections to the internet.

Arguably, this can also happen outside of the test suite. Having the code raise an error seems preferable over a `runtime error: index out of range [0] with length 0`

**Comment by gbraad** [comment]
An empty `resolv.conf` files are possible, as in environments that only depend on IP addresses, this file can be empty. It is unlikely for us to work as expected; though a warning is more appropriate than hard failure (crash) ;-)

**Comment by siretart** [comment]
For the Debian package, I've come up with this patch:

https://salsa.debian.org/go-team/packages/golang-github-containers-gvisor-tap-vsocks/-/blob/debian/sid/debian/patches/0002-Avoid-crash-with-empty-resolv.conf.patch?ref_type=heads

let me know if you prefer me to send this is a PR.

**Comment by evidolob** [comment]
@siretart It would be nice if you make a PR with your fix

**Comment by siretart** [comment]
@evidolob see #420
