### ISSUE TITLE
Reporting failure of net.Dial()s should not occur by default

### ISSUE THREAD

**Issue by fingon** [containers/gvisor-tap-vsock#74]
If running container which attempts to connect somewhere without open port, the code in `pkg/services/forwarder/tcp.go` produces log line (to standard error?) per failed attempt:
```
                        log.Errorf("net.Dial() = %v", err)
```
=>
```
         ERRO[143797] net.Dial() = dial tcp IP:PORT: connect: connection refused 
```

**Comment by guillaumerose** [comment]
Hi, thanks for the report.
Do you think it should be better to keep it as a debug log?

**Comment by fingon** [comment]
I'd just remove it by default, although with some flag it might be useful. 

I don't know what is the default logging configuration, but in whatever it is, this shouldn't be logged as it is not error and due to that not useful.

**Comment by protosam** [comment]
Should be `log.Trace`. PR submitted.

**Comment by guillaumerose** [comment]
Thanks @protosam for the patch!
